# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qframelesswindow import AcrylicWindow

class Ui_MainWindow(object):
    def setupUi(self, centralwidget):
        centralwidget.resize(1200, 900)
        
        centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(centralwidget)
        self.verticalLayout.setContentsMargins(-1, 32, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StausBar = QtWidgets.QFrame(centralwidget)
        self.StausBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StausBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StausBar.setObjectName("StausBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.StausBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SysTitle = QtWidgets.QLabel(self.StausBar)
        self.SysTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.SysTitle.setObjectName("SysTitle")
        self.horizontalLayout.addWidget(self.SysTitle)
        self.progressBar = QtWidgets.QProgressBar(self.StausBar)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.Time = QtWidgets.QLabel(self.StausBar)
        self.Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Time.setObjectName("Time")
        self.horizontalLayout.addWidget(self.Time)
        self.verticalLayout.addWidget(self.StausBar)
        self.WorkSpace = QtWidgets.QFrame(centralwidget)
        self.WorkSpace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WorkSpace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WorkSpace.setObjectName("WorkSpace")
        self.WorkSpace.setStyleSheet("#WorkSpace{\n"
"background-image: url(./logo1.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center center; \n"
"}\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.WorkSpace)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.WorkSpace)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.frame_2 = QtWidgets.QFrame(self.WorkSpace)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ViewImg = QtWidgets.QLabel(self.frame_2)
        self.ViewImg.setEnabled(True)
        self.ViewImg.setStyleSheet("#ViewImg {\n"
"    \n"
"}")
        self.ViewImg.setText("")
        self.ViewImg.setAlignment(QtCore.Qt.AlignCenter)
        self.ViewImg.setObjectName("ViewImg")
        self.verticalLayout_5.addWidget(self.ViewImg)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.WorkSpace)
        self.ToolBar = QtWidgets.QFrame(centralwidget)
        self.ToolBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ToolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ToolBar.setObjectName("ToolBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ToolBar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.ToolBar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.InputLabel = QtWidgets.QLabel(self.frame_4)
        self.InputLabel.setObjectName("InputLabel")
        self.verticalLayout_4.addWidget(self.InputLabel)
        self.OutputLabel = QtWidgets.QLabel(self.frame_4)
        self.OutputLabel.setObjectName("OutputLabel")
        self.verticalLayout_4.addWidget(self.OutputLabel)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.ToolBar)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InputPath = QtWidgets.QLineEdit(self.frame)
        self.InputPath.setObjectName("InputPath")
        self.verticalLayout_2.addWidget(self.InputPath)
        self.OutputPath = QtWidgets.QLineEdit(self.frame)
        self.OutputPath.setObjectName("OutputPath")
        self.verticalLayout_2.addWidget(self.OutputPath)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.ToolBar)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ComboBox = QtWidgets.QComboBox(self.frame_3)
        self.ComboBox.addItems(['Yolov5', 'Yolov8', 'Yolov9'])
        self.verticalLayout_3.addWidget(self.ComboBox)
        self.Start = QtWidgets.QPushButton(self.frame_3)
        self.Start.setObjectName("Start")
        self.verticalLayout_3.addWidget(self.Start)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.ToolBar)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SysTitle.setText(_translate("MainWindow", "钢铁缺陷检测系统"))
        self.Time.setText(_translate("MainWindow", "00:00"))
        self.InputLabel.setText(_translate("MainWindow", "检测路径："))
        self.OutputLabel.setText(_translate("MainWindow", "保存路径："))
        self.InputPath.setText(_translate("MainWindow", "dataset\\IMAGES"))
        self.OutputPath.setText(_translate("MainWindow", "output"))
        self.Start.setText(_translate("MainWindow", "开始检测"))

class Window(AcrylicWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())